// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAou8X8_D52r8VrJm10cG7ICh8XgUuox2c',
    appId: '1:213273213851:web:9920e5fd4b1ae7ab79ff3e',
    messagingSenderId: '213273213851',
    projectId: 'exams-project-e5b5c',
    authDomain: 'exams-project-e5b5c.firebaseapp.com',
    storageBucket: 'exams-project-e5b5c.firebasestorage.app',
    measurementId: 'G-4EQHDXHZRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlWb-MBUYj4zrMWHjSaJ3_vY1sGNfRVvw',
    appId: '1:213273213851:android:1c48fa945b7f2fa379ff3e',
    messagingSenderId: '213273213851',
    projectId: 'exams-project-e5b5c',
    storageBucket: 'exams-project-e5b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACgkkaO65_4vVuFmDocwIJi1-DX_n71Pw',
    appId: '1:213273213851:ios:61003f47a5282dbe79ff3e',
    messagingSenderId: '213273213851',
    projectId: 'exams-project-e5b5c',
    storageBucket: 'exams-project-e5b5c.firebasestorage.app',
    iosBundleId: 'com.example.esame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACgkkaO65_4vVuFmDocwIJi1-DX_n71Pw',
    appId: '1:213273213851:ios:61003f47a5282dbe79ff3e',
    messagingSenderId: '213273213851',
    projectId: 'exams-project-e5b5c',
    storageBucket: 'exams-project-e5b5c.firebasestorage.app',
    iosBundleId: 'com.example.esame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAou8X8_D52r8VrJm10cG7ICh8XgUuox2c',
    appId: '1:213273213851:web:f01cdfb6fb403a7179ff3e',
    messagingSenderId: '213273213851',
    projectId: 'exams-project-e5b5c',
    authDomain: 'exams-project-e5b5c.firebaseapp.com',
    storageBucket: 'exams-project-e5b5c.firebasestorage.app',
    measurementId: 'G-8Z6BCHWN4C',
  );
}
